[project]
name = "car-price-predictor"
version = "0.1.0"
description = "Predicts the Price of used cars based on their condition"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "joblib>=1.5.3",
    "numpy>=2.5.1",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "streamlit>=1.60.0",
]
